Soc/map stuff
BeksOmega/appinventor-sources pull request #16
Opened 2020-07-23 17:09 UTC by BeksOmega

2020-08-16 03:09 UTC, ewpatton requested changes
A few minor things to address.

2020-08-16 03:09 UTC, ewpatton commented on appinventor/blocklyeditor/src/versioning.js
> +           'Map', 'ScaleUnits', 'Units'),
Either line 2068 or 2070 has the wrong indentation. I think this line should be one space to the left.

2020-08-16 03:09 UTC, ewpatton commented on appinventor/blocklyeditor/src/versioning.js
> +      'Navigation', 'TransportationMethod', 'TransportMethod')]
Indentation

2020-08-16 03:09 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/common/MapType.java
> +  private static final Map<Integer, MapType> lookup = new HashMap<>();
After having reviewed a few of these, I'm wondering if we should have a utility method that constructs the HashMap given the class. If so, it could go into a different PR since it's not specific to this change.

2020-08-16 03:09 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/common/Units.java
> +public enum Units implements OptionList<Integer> {
I'd like to rename this ScaleUnits so that in the future if we wanted to have a class with more concrete units (m, cm, ft, etc.) we could. This is more of a class of units rather than a specific set of units.

2020-08-16 20:21 UTC, BeksOmega commented on appinventor/components/src/com/google/appinventor/components/common/MapType.java
> +  private static final Map<Integer, MapType> lookup = new HashMap<>();
Filed an [issue](https://github.com/BeksOmega/appinventor-sources/issues/28#issue-679816867). I'll move it into the main repo if I don't get that change in by the end of August.

2020-08-18 04:01 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/common/MapType.java
> +  private static final Map<Integer, MapType> lookup = new HashMap<>();
@BeksOmega sounds good to me.

2020-08-18 04:03 UTC, ewpatton approved these changes
LGTM

2020-08-18 18:57 UTC, merged